In [7]:
import pandas as pd
import json

In [8]:
df = pd.read_json('export.json')
df
# Clean the 'id' column
# df['id'] = df['id'].apply(lambda x: x['$oid'] if isinstance(x, dict) and '$oid' in x else x)

,_id,user,language,filename,snapcode,subject_code,value,issaved,created_at
0,{'$oid': '64a3cfc43f59546fc1c50302'},hodara,plaintext,Untitled-1,,IDT_ALGO_G2,"[{'action': 'select paste', 'text': ' ""code...",True,{'$date': 1688457156955}
1,{'$oid': '64a3cfd53f59546fc1c50303'},hodara,plaintext,Untitled-1,this testing,IDT_ALGO_G2,"[{'action': 'add', 'text': 't', 'timestamp': 1...",False,{'$date': 1688457173054}
2,{'$oid': '64a3d4173f59546fc1c50304'},hihida,c,c:\Users\LENOVO\Documents\String Practice.c,#include <stdio.h>\r\nint main (){\r\n char st...,IDT_ALGO_G2,"[{'action': 'select paste', 'text': ' ""code...",True,{'$date': 1688458263962}
3,{'$oid': '64a3d4813f59546fc1c50305'},kikhun,plaintext,Untitled-1,hi teachr\r\n,IDT_ALGO_G2,"[{'action': 'add', 'text': 'h', 'timestamp': 1...",False,{'$date': 1688458369468}
4,{'$oid': '64a3d4863f59546fc1c50306'},kikhun,plaintext,Untitled-1,hi teachr\r\n\r\n\r\n\r\n\r\n,IDT_ALGO_G2,"[{'action': 'paste', 'text': ' ', 'timestamp'...",False,{'$date': 1688458374432}
...,...,...,...,...,...,...,...,...,...
94859,{'$oid': '651c224a0b282568f3daa003'},oesinh,html,/Users/macbook/Documents/web_design/web_ass4/i...,"<!DOCTYPE html>\n<html lang=""en"">\n<head>\n ...",IDT_ALGO_G3,"[{'action': 'delete', 'text': '', 'timestamp':...",True,{'$date': 1696342602913}
94860,{'$oid': '651c22550b282568f3daa004'},oesinh,html,/Users/macbook/Documents/web_design/web_ass4/i...,"<!DOCTYPE html>\n<html lang=""en"">\n<head>\n ...",IDT_ALGO_G3,"[{'action': 'delete', 'text': '', 'timestamp':...",True,{'$date': 1696342613217}
94861,{'$oid': '651c22590b282568f3daa005'},oesinh,html,/Users/macbook/Documents/web_design/web_ass4/i...,"<!DOCTYPE html>\n<html lang=""en"">\n<head>\n ...",IDT_ALGO_G3,"[{'action': 'delete', 'text': '', 'timestamp':...",True,{'$date': 1696342617752}
94862,{'$oid': '651c225f0b282568f3daa006'},oesinh,html,/Users/macbook/Documents/web_design/web_ass4/i...,"<!DOCTYPE html>\n<html lang=""en"">\n<head>\n ...",IDT_ALGO_G3,"[{'action': 'delete', 'text': '', 'timestamp':...",True,{'$date': 1696342623428}
94863,{'$oid': '651c22670b282568f3daa007'},oesinh,html,/Users/macbook/Documents/web_design/web_ass4/i...,"<!DOCTYPE html>\n<html lang=""en"">\n<head>\n ...",IDT_ALGO_G3,"[{'action': 'delete', 'text': '', 'timestamp':...",True,{'$date': 1696342631952}

In [11]:
# # Assuming 'data.json' contains your data with the ID column
# with open('export.json', 'r') as json_file:
#     data = json.load(json_file)

# # You can clean the ID column as follows:
# for item in data:
#     if 'id' in item and '$oid' in item['id']:
#         item['id'] = item['id']['$oid']

# # Convert the list of dictionaries to a DataFrame
# df = pd.DataFrame(data)

In [11]:
# Sample DataFrame
data = {'id': [{'$oid': '64a3cfc43f59546fc1c50302'}, {'$oid': '64a3cfc43f59546fc1c50303'}]}
df = pd.DataFrame(data)

# Clean the 'id' column
df['id'] = df['id'].apply(lambda x: x['$oid'] if isinstance(x, dict) and '$oid' in x else x)

# Display the cleaned DataFrame
print(df)

                         id
0  64a3cfc43f59546fc1c50302
1  64a3cfc43f59546fc1c50303

In [24]:
data['id'][0].values()

dict_values(['64a3cfc43f59546fc1c50302'])